"""
Django settings for geoagents project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
from pathlib import Path
from dotenv import load_dotenv
import os


load_dotenv(".env")
load_dotenv(".env.local", override=True)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--@)_(1j*fblx@b9v-c6^u(5mskvj12(z5w!=7y(cxc$c99z%5%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'rest_framework.authtoken',
    'agents_core',
    'agents_tools.apps.AgentsToolsConfig',
    'agents_gis.apps.AgentsGisConfig',
    'agents_llm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geoagents.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geoagents.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("DB_NAME", "geoagents"),
        "USER": os.getenv("DB_USER", "geoagents"),
        "PASSWORD": os.getenv("DB_PASSWORD", "geoagents"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5433"),
        "ATOMIC_REQUESTS": False,
    }
}

# PostGIS remota para datos GIS (opcional)
# Si GIS_REMOTE_DB_HOST está definido se añade el alias "gis_remote"
_gis_remote_host = os.getenv("GIS_REMOTE_DB_HOST", "")
if _gis_remote_host:
    _gis_remote_cfg = {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("GIS_REMOTE_DB_NAME", ""),
        "USER": os.getenv("GIS_REMOTE_DB_USER", ""),
        "PASSWORD": os.getenv("GIS_REMOTE_DB_PASSWORD", ""),
        "HOST": _gis_remote_host,
        "PORT": os.getenv("GIS_REMOTE_DB_PORT", "5432"),
        "ATOMIC_REQUESTS": False,
    }
    _gis_sslmode = os.getenv("GIS_REMOTE_DB_SSLMODE", "")
    if _gis_sslmode:
        _gis_remote_cfg["OPTIONS"] = {"sslmode": _gis_sslmode}
    DATABASES["gis_remote"] = _gis_remote_cfg

# Alias de BD que usan las herramientas GIS
# Poner "gis_remote" para apuntar a la BD remota
AGENTS_GIS_DB_ALIAS = os.getenv("AGENTS_GIS_DB_ALIAS", "default")

# Esquema PostgreSQL donde están las capas GIS
AGENTS_GIS_SCHEMA = os.getenv("AGENTS_GIS_SCHEMA", "public")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}



# Catálogo de capas GIS.
# Si existe gis_layers_catalog.json (generado por inspect_remote_gis) se usa ese;
# de lo contrario se usan las capas demo locales.
_GIS_LAYERS_CATALOG = BASE_DIR / "gis_layers_catalog.json"
if _GIS_LAYERS_CATALOG.exists():
    with open(_GIS_LAYERS_CATALOG, encoding="utf-8") as _f:
        AGENTS_GIS_LAYERS = json.load(_f)
else:
    AGENTS_GIS_LAYERS = [
        {
            "name": "demo_points",
            "table": "demo_points",
            "geom_col": "the_geom",
            "id_col": "id",
            "fields": ["name"],
            "filter_fields": ["name"],
            "geometry_kind": "point",
        },
        {
            "name": "demo_polygons",
            "table": "demo_polygons",
            "geom_col": "the_geom",
            "id_col": "id",
            "fields": ["name"],
            "filter_fields": ["name"],
            "geometry_kind": "polygon",
        },
        {
            "name": "demo_lines",
            "table": "demo_lines",
            "geom_col": "the_geom",
            "id_col": "id",
            "fields": ["name"],
            "filter_fields": ["name"],
            "geometry_kind": "line",
        },
    ]


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
GIS_MAP_LAYER_MAX_FEATURES = int(os.getenv("GIS_MAP_LAYER_MAX_FEATURES", "1000"))
AGENTS_DEFAULT_LLM_MODEL = os.getenv(
    "AGENTS_DEFAULT_LLM_MODEL",
    "gpt-4o-mini"
)
AGENTS_MAX_PLANNER_TOOL_STEPS = int(
    os.getenv("AGENTS_MAX_PLANNER_TOOL_STEPS", "5")
)
if not OPENAI_API_KEY:
    raise RuntimeError("OPENAI_API_KEY not configured")