# Generated by Django 6.0.3 on 2026-03-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('system', 'System'), ('plan', 'Plan'), ('llm', 'LLM'), ('tool', 'Tool'), ('result', 'Result'), ('error', 'Error')], max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('input_json', models.JSONField(blank=True, default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents_core.run')),
            ],
            options={
                'ordering': ['run_id', 'idx'],
                'indexes': [models.Index(fields=['run', 'idx'], name='agents_core_run_id_d5def4_idx'), models.Index(fields=['run', 'kind'], name='agents_core_run_id_06b72e_idx')],
            },
        ),
    ]
