# Generated by Django 6.0.3 on 2026-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_core', '0002_runstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tool_allowlist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='run',
            name='step_seq',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
