# Generated by Django 6.0.3 on 2026-03-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_core', '0003_agent_tool_allowlist_run_step_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='final_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
