# Generated by Django 6.0.3 on 2026-03-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_core', '0004_run_final_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile',
            field=models.CharField(choices=[('compact', 'Compact'), ('rich', 'Rich'), ('investigate', 'Investigate')], default='compact', max_length=20),
        ),
    ]
