# Generated by Django 6.0.3 on 2026-03-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents_core", "0005_agent_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodePattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("goal_signature", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("domain", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "tool_sequence_signature",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("tool_sequence", models.JSONField(blank=True, default=list)),
                ("sample_size", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("last_outcome_status", models.CharField(blank=True, default="", max_length=32)),
                ("last_failure_mode", models.CharField(blank=True, default="", max_length=255)),
                ("recommended_strategy", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["domain", "success_rate"], name="agents_core_domain_7cbf7b_idx"),
                    models.Index(fields=["goal_signature", "success_rate"], name="agents_core_goal_si_b85502_idx"),
                ],
                "unique_together": {("goal_signature", "domain", "tool_sequence_signature")},
            },
        ),
        migrations.CreateModel(
            name="RunMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("normalized_goal", models.TextField(blank=True, default="")),
                ("goal_signature", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("domain", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("analysis_types", models.JSONField(blank=True, default=list)),
                ("analysis_types_search", models.TextField(blank=True, default="")),
                ("layers", models.JSONField(blank=True, default=list)),
                ("layers_search", models.TextField(blank=True, default="")),
                ("tools_used", models.JSONField(blank=True, default=list)),
                ("tools_search", models.TextField(blank=True, default="")),
                (
                    "tool_sequence_signature",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("final_plan", models.JSONField(blank=True, default=dict)),
                ("plan_history", models.JSONField(blank=True, default=list)),
                ("structured_results", models.JSONField(blank=True, default=dict)),
                ("verification_summary", models.JSONField(blank=True, default=dict)),
                ("verification_status", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("outcome", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("failure_modes", models.JSONField(blank=True, default=list)),
                ("failure_modes_search", models.TextField(blank=True, default="")),
                ("replans", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="memory", to="agents_core.run"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["domain", "verification_status"], name="agents_core_domain_35981f_idx"),
                    models.Index(fields=["goal_signature", "tool_sequence_signature"], name="agents_core_goal_si_78867c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("normalized_goal", models.TextField(blank=True, default="")),
                ("goal_signature", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("domain", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("analysis_types", models.JSONField(blank=True, default=list)),
                ("tools_used", models.JSONField(blank=True, default=list)),
                ("tool_sequence", models.JSONField(blank=True, default=list)),
                (
                    "tool_sequence_signature",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("outcome_status", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("verification_status", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("success", models.BooleanField(default=False)),
                ("failure_mode", models.CharField(blank=True, default="", max_length=255)),
                ("failure_modes", models.JSONField(blank=True, default=list)),
                ("recommended_strategy", models.TextField(blank=True, default="")),
                ("verification_summary", models.JSONField(blank=True, default=dict)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("replan_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="episode", to="agents_core.run"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["goal_signature", "domain"], name="agents_core_goal_si_0bf9b5_idx"),
                    models.Index(fields=["tool_sequence_signature", "success"], name="agents_core_tool_se_604d2f_idx"),
                ],
            },
        ),
    ]
