# Generated by Django 6.0.3 on 2026-03-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_core', '0006_runmemory_episode_episodepattern'),
        ('agents_core', '0007_alter_agent_id_alter_run_id_alter_runstep_id'),
    ]

    operations = [
    ]
