# Generated by Django 5.2.12 on 2026-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_core', '0008_merge_20260323_1116'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='episode',
            new_name='agents_core_goal_si_5f5d83_idx',
            old_name='agents_core_goal_si_0bf9b5_idx',
        ),
        migrations.RenameIndex(
            model_name='episode',
            new_name='agents_core_tool_se_1d6301_idx',
            old_name='agents_core_tool_se_604d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='episodepattern',
            new_name='agents_core_domain_6f1f0f_idx',
            old_name='agents_core_domain_7cbf7b_idx',
        ),
        migrations.RenameIndex(
            model_name='episodepattern',
            new_name='agents_core_goal_si_dda41e_idx',
            old_name='agents_core_goal_si_b85502_idx',
        ),
        migrations.RenameIndex(
            model_name='runmemory',
            new_name='agents_core_domain_89bcbd_idx',
            old_name='agents_core_domain_35981f_idx',
        ),
        migrations.RenameIndex(
            model_name='runmemory',
            new_name='agents_core_goal_si_f2f78b_idx',
            old_name='agents_core_goal_si_78867c_idx',
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episodepattern',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='run',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runmemory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runstep',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
