# Generated by Django 6.0.3 on 2026-04-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_core', '0009_rename_agents_core_goal_si_0bf9b5_idx_agents_core_goal_si_5f5d83_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='gis_catalog_updated_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se ejecutó la introspección del catálogo.', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='gis_db_connections',
            field=models.JSONField(blank=True, default=list, help_text='Conexiones a BBDDs GIS remotas de este agente.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='gis_layers_catalog',
            field=models.JSONField(blank=True, default=list, help_text='Catálogo de capas GIS. Se regenera automáticamente al guardar conexiones.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episodepattern',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='run',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runmemory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runstep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
