# Generated by Django 6.0.3 on 2026-04-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_core', '0010_agent_gis_connections_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Sesión conversacional. Runs con el mismo session_id reciben contexto de turnos anteriores.', max_length=64),
        ),
    ]
