from typing import Sequence


TOOL_ANALYSIS_TYPES = {
    "spatial.aggregate": "statistical_aggregation",
    "spatial.buffer": "proximity_analysis",
    "spatial.centroid": "geometry_operation",
    "spatial.cluster_dbscan": "clustering",
    "spatial.context_pack": "spatial_context",
    "spatial.convex_hull": "geometry_operation",
    "spatial.count_within": "statistical_aggregation",
    "spatial.difference": "geometry_operation",
    "spatial.dissolve": "geometry_operation",
    "spatial.grid_stats": "density_analysis",
    "spatial.intersects": "spatial_relation",
    "spatial.measure": "geometry_measurement",
    "spatial.nearest_neighbor": "proximity_analysis",
    "spatial.network_service_area": "network_service_area",
    "spatial.network_trace": "network_trace",
    "spatial.overlay": "geometry_operation",
    "spatial.query_layer": "layer_query",
    "spatial.route_cost": "network_route_cost",
    "spatial.spatial_join": "spatial_relation",
    "spatial.summary": "spatial_summary",
    "spatial.topology_check": "quality_check",
    "spatial.voronoi": "geometry_operation",
    "spatial.within_distance": "proximity_analysis",
}

KEYWORD_ANALYSIS_TYPES = {
    "agrup": "statistical_aggregation",
    "buffer": "proximity_analysis",
    "centroide": "geometry_operation",
    "centroid": "geometry_operation",
    "cluster": "clustering",
    "cobertura": "network_service_area",
    "coste": "network_route_cost",
    "costo": "network_route_cost",
    "debug": "debugging",
    "densidad": "density_analysis",
    "depura": "debugging",
    "disuelve": "geometry_operation",
    "dissolve": "geometry_operation",
    "errores geomet": "quality_check",
    "envolvente": "geometry_operation",
    "estadistic": "statistical_aggregation",
    "fallback": "resilience",
    "fusiona": "geometry_operation",
    "grafo": "network_trace",
    "hotspot": "clustering",
    "interse": "spatial_relation",
    "invalida": "quality_check",
    "isocron": "network_service_area",
    "longitud total": "geometry_measurement",
    "mapa de calor": "density_analysis",
    "mas cercano": "proximity_analysis",
    "mas cercana": "proximity_analysis",
    "mide": "geometry_measurement",
    "network": "network_trace",
    "proxim": "proximity_analysis",
    "red": "network_trace",
    "replan": "replanning",
    "ruta": "network_trace",
    "servicio": "network_service_area",
    "solap": "spatial_relation",
    "superficie total": "geometry_measurement",
    "topolog": "quality_check",
    "trace": "network_trace",
    "validez": "quality_check",
    "voronoi": "geometry_operation",
}


def tool_sequence_signature(tools_used: Sequence[str]) -> str:
    sequence = [tool.strip() for tool in (tools_used or []) if tool and tool.strip()]
    return ">".join(sequence) if sequence else "none"
